### ISSUE TITLE
[Bug] Tv mode not working while being on tv

### ISSUE THREAD

**Issue by xxRaiyanxxYT** [Nanoc6/SaikouTV#1]
Hello i have tried to install SaikouTV on my android TV but the tv ui doesn't appear in my tv though

its still the same as the android ui,,,,, I have tried closing and opening the app / Reinstalling old[Launching SaikouTV 1.0.5 From home screen](https://imgur.com/a/L7r5foy) er versions but that didn't work.

### Here a pic of the issue tho:

> ![PXL_20220421_131302191](https://user-images.githubusercontent.com/45197348/164594309-7b0ab630-8173-4df4-a74d-30a947569ae1.jpg)
  `    its still in android ui  (More like in tablet mode)    `

_So i think theres two possible reasons for this issue (i could think of):_

-  Probably something wrong with my Tv dpi or screensize

-  Or the value for tv screensizes are high

Mhm i think this is fixable by adding an option to
**force into tv mode** in settings if the app can't automatically detect tv screens (like mine ig) .

_Oh also here are the tv specs if you're wondering_:

- Vendor: Singer

- Tv screen res and size: ~28 inch (Applies to screen) / 1920 x 1080p

- SoC: mt5863

- Android ver: 7.0

- Cpu-Architecture: Armabi-v7a

**Comment by Nanoc6** [comment]
Are you using the android TV leanback launcher? could you share an image of the main screen where you launch saikou?

**Comment by xxRaiyanxxYT** [comment]
@Nanoc6 
> Are you using the android TV leanback launcher? could you share an image of the main screen where you launch saikou?

Nope I don't think they use android TV leanback launcher by Google. They are using their own custom made launcher i guess.
Also sureee 
### heres a clip of me launching SaikouTV 1.0.5 from home screen:

> https://imgur.com/a/L7r5foy

### Btw looks like SaikouTV 1.0.6 Fixed the "TV mode" it properly goes into TV mode now but it crashes:

> https://imgur.com/a/mKjw6n0

Also Thanks for your hard work dev 👍✨

**Comment by Nanoc6** [comment]
Please install the new 1.0.7 release, it will probably still crash but i should be getting crash reports now, please try to run it a couple of times to ensure i get crash reports. Thanks

**Comment by xxRaiyanxxYT** [comment]
> Please install the new 1.0.7 release, it will probably still crash but i should be getting crash reports now, please try to run it a couple of times to ensure i get crash reports. Thanks

Doneeee i have opened the app like 20+ times and it crashed after 1 sec
i hope you got the logs tho 👀
also i forgot to add the info that the tv's Cpu architecture is Arm-v7a or smth
(just saying if that has to do something with the crashes)

**Comment by Nanoc6** [comment]
Should be fixed in release 1.0.8, if not please reopen this issue
