### ISSUE TITLE
Uncouple head repo, adapt updater for fork

### ISSUE THREAD

**Issue by morpheasgr** [Nanoc6/SaikouTV#14]
It would be dope if you could adjust the updater functionality to offer updates for this fork. If I am not mistaken it still looks within the head repo. If you are having difficulties with the API maybe it is because this repo is forked so there are some limitations. By the way, I highly suggest you clone the upstream into a branch here, you could use a bot called 'Pull' for that.

Thanks for keeping the fork updated by the way. I still wish we could find a non-destructive way to incorporate a TV layout or simply and plainly remote support within the main up so you do not need to maintain this fork. Or if shivam cluld make you a collaborator and give you a tv dev branch, where he can moderate and merge tv layout-specific changes into the master/main branch.

**Comment by Nanoc6** [comment]
The updater should be pointing to the latest release on this github, maybe it got broken on a merge, ill check on it.

A TV specific layout is imho much faster and easier to use, manually handling focus through events is a nightmare and yeah this could be on the main repo but thats not on my side.
