### ISSUE TITLE
I can't click at anything

### ISSUE THREAD

**Issue by jashan2774** [Nanoc6/SaikouTV#2]
Whenever I download SaikouTV , I can't click at anything on my fire Tv stick. I have tried to download other versions as well but nothing worked.

**Comment by Nanoc6** [comment]
can you share a screen of what you are seeing? have you tried to click back until it closes then opening it again?

**Comment by jashan2774** [comment]
> can you share a screen of what you are seeing? have you tried to click back until it closes then opening it again?
![16507302547892250223967278392536](https://user-images.githubusercontent.com/104197722/164914175-a3f67ef3-7554-44e9-a24c-14586b5f35f0.jpg)
For like 2 seconds this pops up and then the app closes automatically

**Comment by Nanoc6** [comment]
Thats correct, if the loading never ends please make sure the time settings of your device is OK

**Comment by jashan2774** [comment]
What region's time should i set(Btw I'm from Germany).

**Comment by Nanoc6** [comment]
You don't need to set a specific region, just make sure it's on time.

If it is and still never ends something may be blocked on your connection, if that's the case it could be useful to check if the phone app works on the same connection as it will probably give you some more info.

**Comment by jashan2774** [comment]
> You don't need to set a specific region, just make sure it's on time.
> 
> If it is and still never ends something may be blocked on your connection, if that's the case it could be useful to check if the phone app works on the same connection as it will probably give you some more info.

Thanks for your help 😊

**Comment by Kratos14** [comment]
> > You don't need to set a specific region, just make sure it's on time.
> > If it is and still never ends something may be blocked on your connection, if that's the case it could be useful to check if the phone app works on the same connection as it will probably give you some more info.
> 
> Thanks for your help 😊

How did you solve it? I just got a fire tv stick and i have the same issue.
