### ISSUE TITLE
Version 1.0.14 no longer requires anilist login to block 18+ content

### ISSUE THREAD

**Issue by intellimediatv** [Nanoc6/SaikouTV#21]
How come the new TV version 1.0.14 suddenly gives free access to Hentai without logging into Anilist to turn 18+  content on are the devs aware of this

**Comment by Shemar890** [comment]
![Screenshot_20221110-165839_Saikou .jpg](https://user-images.githubusercontent.com/106935450/201214908-73db2711-26b7-4d8a-913e-d9420452ba18.jpg)

**Comment by Nanoc6** [comment]
I am aware, i totally do not support requiring an account to see +18 content.

A On/Off switch (defaulted to Off) will be added on the settings screen in the future
