### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by JimZiii** [Nanoc6/SaikouTV#5]
I can't find the phone login in the regular saikou app, do you really want people to uninstall the regular app and install the tv version on their phone just to login? Or have i misunderstood that whole process?

If i use the web browser login i get this after typing in my login details
![16514890489634804416213382359732](https://user-images.githubusercontent.com/7854537/166223701-e0f337d0-89b8-4506-a48d-f6a7b7bb0c37.jpg)

I've tried several times now with the same outcome

**Comment by Nanoc6** [comment]
Yes, until it gets merged upstream, if webrowser login method doesn't work for you (and its weird cause you seem to somehow get stuck at very last part of the process) you need to install TV version on your phone to login, it is really the best way to login on TV and the mobile version should be unchanged except for the obvious tv login option

**Comment by JimZiii** [comment]
> Yes, until it gets merged upstream, if webrowser login method doesn't work for you (and its weird cause you seem to somehow get stuck at very last part of the process) you need to install TV version on your phone to login, it is really the best way to login on TV and the mobile version should be unchanged except for the obvious tv login option

Ok thnx, yea i installed the tv version and logged in after my last comment and then installed the regular phone version again since i wasn't sure if the tv version were up to date with the phone version or not.

So we can expect them to merge in the future, that's great.
Just found the app yesterday and it's great, it's really appreciated that you picked up the tv dev side of it.

**Comment by CR1MS0N24** [comment]
I found a solution
