### ISSUE TITLE
Unable To Change Quality in TV

### ISSUE THREAD

**Issue by GHOUL77** [Nanoc6/SaikouTV#7]
Cant change quality in any server.

**Comment by Nanoc6** [comment]
Can you please provide some more info? Does the HD button shows? does the selection dialog appear?

**Comment by GHOUL77** [comment]
Yes the selection dialog box appears but it is only about the server . Ex - Stream SB ,etc .

**Comment by GHOUL77** [comment]
Ok The issue is fixed in the latest version. Thanks!
